Repository team401/2024-Robot-Code, pull requests merged in 2024-02, with the labels that each got.

#68 Avoid Simulator Crash and Un-Break Telemetry
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/endgame/EndgameSimIO.java
Labels: urgent

#71 Document scoring subsystem and add converter for csv to mermaid
  doc/Intake.md
  doc/Scoring.md
  doc/intake.csv
  doc/scoring.csv
  util/secretary/README.md
  util/secretary/driver.py
  util/secretary/secretary.py
Labels: documentation

#76 Adds lookup table for stage avoidance
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/scoring/ScoringSubsystem.java
Labels: scoring

#78 Adjusts left and right flywheel speeds to be different
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/scoring/ScoringSubsystem.java
  src/main/java/frc/robot/subsystems/scoring/ShooterIO.java
  src/main/java/frc/robot/subsystems/scoring/ShooterIOSim.java
  src/main/java/frc/robot/subsystems/scoring/ShooterIOTalon.java
Labels: scoring

#87 Adds 2024 drive tuning constants
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
Labels: bug, drivetrain

#108 Fixes teleop init bug
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
Labels: bug

#109 Adds scoring overrides
  src/main/java/frc/robot/subsystems/scoring/ScoringSubsystem.java
Labels: feature, scoring

#115 Brake switch integration (#114)
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/endgame/EndgameIO.java
  src/main/java/frc/robot/subsystems/endgame/EndgameIOSparkFlex.java
  src/main/java/frc/robot/subsystems/endgame/EndgameSubsystem.java
  src/main/java/frc/robot/subsystems/scoring/AimerIOTalon.java
  src/main/java/frc/robot/subsystems/scoring/ScoringSubsystem.java
Labels: feature
